// frontend/react-app/src/pages/EmployeeList.tsx
import { useState, useEffect } from "react";
import { Employee, EmployeeDto, Department } from "../types/models";
import * as employeeService from "../services/employeeService";
import * as departmentService from "../services/departmentService";
import { Button, Table, Spinner, Alert, Modal, Form } from "react-bootstrap";
import { toast } from "react-toastify";

export const EmployeeList = () => {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [departmentMap, setDepartmentMap] = useState<Map<number, string>>(
    new Map()
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // --- State for Modals ---
  const [showFormModal, setShowFormModal] = useState(false);
  const [currentEmployee, setCurrentEmployee] = useState<Employee | null>(null);
  const [formData, setFormData] = useState<EmployeeDto>({
    name: "",
    email: "",
    phone: "",
    salary: 0,
    departmentId: 0,
  });

  const fetchData = async () => {
    try {
      !loading && setLoading(true);
      const [empResponse, deptResponse] = await Promise.all([
        employeeService.getEmployees(),
        departmentService.getDepartments(),
      ]);

      setEmployees(empResponse.data);
      setDepartments(deptResponse.data);

      const deptMap = new Map<number, string>();
      deptResponse.data.forEach((d) => deptMap.set(d.departmentId, d.name));
      setDepartmentMap(deptMap);
      setError(null);
    } catch (err) {
      setError("Failed to fetch application data.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  // --- Employee Form Modal Handlers ---
  const handleShowFormModal = (employee: Employee | null = null) => {
    setCurrentEmployee(employee);
    if (employee) {
      setFormData({
        name: employee.name,
        email: employee.email,
        phone: employee.phone,
        salary: employee.salary,
        departmentId: employee.departmentId,
      });
    } else {
      setFormData({
        name: "",
        email: "",
        phone: "",
        salary: 0,
        departmentId: departments[0]?.departmentId ?? 0,
      });
    }
    setShowFormModal(true);
  };
  const handleCloseFormModal = () => setShowFormModal(false);

  // --- Generic Form & Delete Handlers ---
  const handleFormChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: ["salary", "departmentId"].includes(name) ? Number(value) : value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (currentEmployee) {
        await employeeService.updateEmployee(
          currentEmployee.employeeId,
          formData
        );
        toast.success(`Employee "${formData.name}" updated!`);
      } else {
        await employeeService.addEmployee(formData);
        toast.success(`Employee "${formData.name}" created!`);
      }
      fetchData();
      handleCloseFormModal();
    } catch (err) {
      toast.error("Failed to save employee.");
      console.error("Failed to save employee", err);
    }
  };

  const handleDelete = async (employee: Employee) => {
    if (window.confirm(`Are you sure you want to delete ${employee.name}?`)) {
      try {
        await employeeService.deleteEmployee(employee.employeeId);
        toast.success(`Employee "${employee.name}" deleted!`);
        fetchData();
      } catch (err) {
        toast.error("Failed to delete employee.");
        console.error("Failed to delete employee", err);
      }
    }
  };

  if (loading)
    return (
      <div className="text-center p-5">
        <Spinner
          animation="border"
          style={{ color: "var(--primary-orange)" }}
        />
      </div>
    );
  if (error) return <Alert variant="danger">{error}</Alert>;

  return (
    <>
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 style={{ color: "var(--text-dark)", fontWeight: 700 }}>
            Employee Management
          </h1>
          <p style={{ color: "var(--text-light)" }}>
            Manage all employee records in your organization.
          </p>
        </div>
        <Button
          onClick={() => handleShowFormModal()}
          style={{
            backgroundColor: "var(--primary-orange)",
            borderColor: "var(--primary-orange)",
          }}
        >
          + Add Employee
        </Button>
      </div>

      <div className="bg-white rounded-3 shadow-sm">
        <Table responsive="sm" hover>
          <thead style={{ backgroundColor: "#f8fafc" }}>
            <tr>
              <th className="p-3">ID</th>
              <th className="p-3">Name</th>
              <th className="p-3">Email</th>
              <th className="p-3">Department</th>
              <th className="p-3 text-end">Actions</th>
            </tr>
          </thead>
          <tbody>
            {employees.map((emp) => (
              <tr key={emp.employeeId}>
                <td className="p-3">{emp.employeeId}</td>
                <td className="p-3 fw-medium">{emp.name}</td>
                <td className="p-3">{emp.email}</td>
                <td className="p-3">
                  {departmentMap.get(emp.departmentId) ?? "N/A"}
                </td>
                <td className="p-3 text-end">
                  <Button
                    variant="link"
                    style={{ color: "var(--text-link-edit)" }}
                    className="fw-medium me-2"
                    onClick={() => handleShowFormModal(emp)}
                  >
                    Edit
                  </Button>
                  <Button
                    variant="link"
                    style={{ color: "var(--text-link-delete)" }}
                    className="fw-medium"
                    onClick={() => handleDelete(emp)}
                  >
                    Delete
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </Table>
      </div>

      {/* Employee Add/Edit Modal */}
      <Modal show={showFormModal} onHide={handleCloseFormModal}>
        <Modal.Header closeButton>
          <Modal.Title>{currentEmployee ? "Edit" : "Add"} Employee</Modal.Title>
        </Modal.Header>
        <Form onSubmit={handleSubmit}>
          <Modal.Body>
            <Form.Group className="mb-3">
              <Form.Label>Full Name</Form.Label>
              <Form.Control
                type="text"
                name="name"
                value={formData.name}
                onChange={handleFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Email</Form.Label>
              <Form.Control
                type="email"
                name="email"
                value={formData.email}
                onChange={handleFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Phone</Form.Label>
              <Form.Control
                type="text"
                name="phone"
                value={formData.phone}
                onChange={handleFormChange}
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Salary (LKR)</Form.Label>
              <Form.Control
                type="number"
                name="salary"
                value={formData.salary}
                onChange={handleFormChange}
                required
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Department</Form.Label>
              <Form.Select
                name="departmentId"
                value={formData.departmentId}
                onChange={handleFormChange}
                required
              >
                {departments.map((d) => (
                  <option key={d.departmentId} value={d.departmentId}>
                    {d.name}
                  </option>
                ))}
              </Form.Select>
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={handleCloseFormModal}>
              Cancel
            </Button>
            <Button
              type="submit"
              style={{
                backgroundColor: "var(--primary-orange)",
                borderColor: "var(--primary-orange)",
              }}
            >
              Save Changes
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </>
  );
};

// frontend/angular-app/src/app/features/employee-list/employee-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  signal,
} from "@angular/core";
import { CommonModule, TitleCasePipe, CurrencyPipe } from "@angular/common";
import { forkJoin, map } from "rxjs";
import { MatDialog } from "@angular/material/dialog";
import { MatSnackBar } from "@angular/material/snack-bar";

// Models and Services
import { EmployeeService } from "../../core/services/employee.service";
import { DepartmentService } from "../../core/services/department.service";
import { Employee, EmployeeDto } from "../../core/models/employee.model";
import { EmployeeFormComponent } from "../employee-form/employee-form.component";

// Material Imports
import { MatTableModule } from "@angular/material/table";
import { MatIconModule } from "@angular/material/icon";
import { MatButtonModule } from "@angular/material/button";
import { MatProgressSpinnerModule } from "@angular/material/progress-spinner";

type State = { employees: Employee[]; loading: boolean; error: string | null };

@Component({
  selector: "app-employee-list",
  template: `
    <div class="relative">
      <!-- Header -->
      <div class="header-container">
        <div>
          <h1 class="header-title">Employee Management Portal</h1>
          <p class="header-subtitle">
            Manage all employee records in your organization.
          </p>
        </div>
        <button mat-flat-button class="add-button" (click)="onAdd()">
          <mat-icon>add</mat-icon>
          <span>Add Employee</span>
        </button>
      </div>

      <!-- Table -->
      <div class="table-container">
        @switch (status()) { @case ('loading') {
        <div class="state-container">
          <mat-spinner diameter="40"></mat-spinner>
        </div>
        } @case ('error') {
        <div class="state-container">{{ state().error }}</div>
        } @case ('success') {
        <table mat-table [dataSource]="state().employees">
          <ng-container matColumnDef="employeeId">
            <th mat-header-cell *matHeaderCellDef>ID</th>
            <td mat-cell *matCellDef="let row">{{ row.employeeId }}</td>
          </ng-container>
          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef>Name</th>
            <td mat-cell *matCellDef="let row" class="font-medium">
              {{ row.name | titlecase }}
            </td>
          </ng-container>
          <ng-container matColumnDef="email">
            <th mat-header-cell *matHeaderCellDef>Email</th>
            <td mat-cell *matCellDef="let row">{{ row.email }}</td>
          </ng-container>
          <ng-container matColumnDef="department">
            <th mat-header-cell *matHeaderCellDef>Department</th>
            <td mat-cell *matCellDef="let row">{{ row.departmentName }}</td>
          </ng-container>
          <ng-container matColumnDef="salary">
            <th mat-header-cell *matHeaderCellDef class="text-right">Salary</th>
            <td mat-cell *matCellDef="let row" class="text-right font-mono">
              {{ row.salary | currency: "LKR " }}
            </td>
          </ng-container>
          <ng-container matColumnDef="actions">
            <th mat-header-cell *matHeaderCellDef class="text-center">
              Actions
            </th>
            <td mat-cell *matCellDef="let row" class="text-center">
              <button class="action-btn edit-btn" (click)="onEdit(row)">
                Edit
              </button>
              <button class="action-btn delete-btn" (click)="onDelete(row)">
                Delete
              </button>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr
            mat-row
            *matRowDef="let row; columns: displayedColumns"
            class="table-row"
          ></tr>
        </table>
        @if (state().employees.length === 0 && !state().loading) {
        <div class="state-container">No employees found.</div>
        } } }
      </div>
    </div>
  `,
  styles: `
    .header-container { 
      margin-bottom: 1.5rem; 
      display: flex; 
      align-items: center; 
      justify-content: space-between;
    }
    .header-title { font-size: 1.5rem; font-weight: 700; color: var(--text-dark); }
    .header-subtitle { font-size: 0.875rem; color: var(--text-light); }
    .add-button {
      background-color: var(--primary-orange);
      color: white;
    }
    .add-button:hover {
      background-color: var(--primary-orange-hover);
    }
    .table-container {
      background-color: var(--surface-bg);
      border-radius: 0.5rem;
      box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
      overflow: hidden;
    }
    .mat-mdc-header-cell {
      background-color: var(--page-bg);
      color: var(--text-dark);
      font-weight: 600;
      text-transform: uppercase;
      font-size: 0.75rem;
    }
    .table-row:hover { background-color: #f8fafc; }
    .font-medium { font-weight: 500; }
    .font-mono { font-family: monospace; }
    .text-right { text-align: right; }
    .text-center { text-align: center; }
    .action-btn { 
      background: none; 
      border: none; 
      cursor: pointer; 
      font-weight: 500;
      margin: 0 0.5rem;
    }
    .edit-btn { color: var(--text-link-edit); }
    .delete-btn { color: var(--text-link-delete); }
    .state-container { padding: 2rem; text-align: center; color: var(--text-light); }
  `,
  imports: [
    CommonModule,
    MatTableModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EmployeeListComponent {
  private employeeService = inject(EmployeeService);
  private departmentService = inject(DepartmentService);
  private dialog = inject(MatDialog);
  private snackBar = inject(MatSnackBar);

  state = signal<State>({ employees: [], loading: true, error: null });
  status = computed(() => {
    if (this.state().loading) return "loading";
    if (this.state().error) return "error";
    return "success";
  });

  displayedColumns = [
    "employeeId",
    "name",
    "email",
    "department",
    "salary",
    "actions",
  ];

  constructor() {
    this.loadData();
  }

  loadData(): void {
    this.state.update((s) => ({ ...s, loading: true }));
    forkJoin({
      employees: this.employeeService.getEmployees(),
      departments: this.departmentService.getDepartments(),
    })
      .pipe(
        map(({ employees, departments }) => {
          const deptMap = new Map(
            departments.map((d) => [d.departmentId, d.name])
          );
          return employees.map((e) => ({
            ...e,
            departmentName: deptMap.get(e.departmentId) ?? "N/A",
          }));
        })
      )
      .subscribe({
        next: (employees) =>
          this.state.set({ employees, loading: false, error: null }),
        error: (err) =>
          this.state.set({
            employees: [],
            loading: false,
            error: "Could not load employee data.",
          }),
      });
  }

  onAdd(): void {
    const dialogRef = this.dialog.open(EmployeeFormComponent, {
      width: "450px",
    });
    dialogRef.afterClosed().subscribe((result: EmployeeDto | undefined) => {
      if (result) {
        this.employeeService.addEmployee(result).subscribe(() => {
          this.snackBar.open("Employee added successfully!", "OK", {
            duration: 3000,
          });
          this.loadData();
        });
      }
    });
  }

  onEdit(employee: Employee): void {
    const dialogRef = this.dialog.open(EmployeeFormComponent, {
      width: "450px",
      data: employee,
    });
    dialogRef.afterClosed().subscribe((result: EmployeeDto | undefined) => {
      if (result) {
        this.employeeService
          .updateEmployee(employee.employeeId, result)
          .subscribe(() => {
            this.snackBar.open("Employee updated successfully!", "OK", {
              duration: 3000,
            });
            this.loadData();
          });
      }
    });
  }

  onDelete(employee: Employee): void {
    if (confirm(`Are you sure you want to delete ${employee.name}?`)) {
      this.employeeService.deleteEmployee(employee.employeeId).subscribe(() => {
        this.snackBar.open("Employee deleted successfully!", "OK", {
          duration: 3000,
        });
        this.loadData();
      });
    }
  }
}
